build:
  target: docroot
  build_file: build.make

prebuild-commands:
# - 'shell command 1 goes here'# - 'shell command 2 goes here'

# Custom commands. These are run after subtrees are updated and after the drush make
# rebuild runs, before any changes from drush make are committed.
postbuild-commands:
  - 'rm -rf docroot/sites; cd docroot; ln -s ../sites sites'
  - 'rm -rf docroot/.htaccess; cd docroot; ln-s ../.htaccess .htaccess'
  - 'rm -rf docroot/robots.txt; cd docroot; ln-s ../robots.txt robots.txt'
  - 'rm docroot/profiles/dkan/.gitignore'
  - 'rm docroot/profiles/dkan/libraries/Leaflet/.gitignore'
  # If your site includes libraries installed by composer (e.g. composer_autoload
  # or guzzle module) you'll want to include something like this:
  # - 'cd docroot/sites/all/modules/guzzle; composer install;

subtrees:
  dkan:
    path: dkan
    uri: 'git@github.com:nuams/dkan.git'
    branch: 7.x-1.x
    message: 'dkan subtree from git@github.com:nuams/dkan.git'
  geo_file_entity:
    path: geo_file_entity
    uri: 'git@github.com:nuams/geo_file_entity.git'
    branch: master
    message: 'geo_file_entity subtree from git@github.com:nuams/geo_file_entity.git'
  visualization_entity:
    path: visualization_entity
    uri: 'git@github.com:nuams/visualization_entity.git'
    branch: entity_display
    message: 'visualization_entity subtree from git@github.com:nuams/visualization_entity.git'
